services:
  shell:
    entrypoint:
      - /bin/sh
    image: ghcr.io/williamjacksn/yt-dlp
    init: true
    volumes:
      - ./:/home/python/docker-yt-dlp
    working_dir: /home/python/docker-yt-dlp
