services:
  get-mp3:
    entrypoint:
      - /home/python/venv/bin/yt-dlp
      - --extract-audio
      - --audio-format
      - mp3
    image: ghcr.io/williamjacksn/yt-dlp
    init: true
    volumes:
      - ./:/home/python/docker-yt-dlp
    working_dir: /home/python/docker-yt-dlp

  get-mp3-playlist:
    entrypoint:
      - /home/python/venv/bin/yt-dlp
      - --extract-audio
      - --audio-format
      - mp3
      - --cache-dir
      - /home/python/docker-yt-dlp/.local/cache
      - --ignore-errors
      - --continue
      - --no-overwrites
      - --download-archive
      - /home/python/docker-yt-dlp/.local/progress.txt
    image: ghcr.io/williamjacksn/yt-dlp
    init: true
    volumes:
      - ./:/home/python/docker-yt-dlp
    working_dir: /home/python/docker-yt-dlp

  get-mp4:
    entrypoint:
      - /home/python/venv/bin/yt-dlp
      - --format
      - mp4
    image: ghcr.io/williamjacksn/yt-dlp
    init: true
    volumes:
      - ./:/home/python/docker-yt-dlp
    working_dir: /home/python/docker-yt-dlp

  pip-compile:
    entrypoint:
      - /home/python/venv/bin/pip-compile
    image: ghcr.io/williamjacksn/pip-tools:py3.12
    init: true
    volumes:
      - ./:/home/python/thycotic-secret-server-api
    working_dir: /home/python/thycotic-secret-server-api

  shell:
    entrypoint:
      - /bin/sh
    image: ghcr.io/williamjacksn/yt-dlp
    init: true
    volumes:
      - ./:/home/python/docker-yt-dlp
    working_dir: /home/python/docker-yt-dlp
